version: "3.2"
services:
    cadvisor:
        image: google/cadvisor
        hostname: '{{.Node.ID}}'
        command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
        deploy:
          mode: global

    influxdb:
        image: influxdb
        volumes:
            - influx:/var/lib/influxdb
        deploy:
          placement:
            constraints:
              - node.role != manager
          resources:
            limits:
              memory: 350M

    grafana:
        image: grafana/grafana:5.4.3
        ports:
            - 0.0.0.0:3000:3000
        volumes:
            - grafana:/var/lib/grafana

volumes:
    influx:
        driver: local
    grafana:
        driver: local
