{
 "title": "cAdvisor with InfluxDB",
 "description": "This dashboard json is from https://github.com/botleg/swarm-monitoring. I did nothing! Because there isn't the json file in grafana homepage, I upload by myself :D",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values with key = \"machine\""
   },
   {
    "name": "container",
    "label": "Container",
    "query": "show tag values with key = \"container_name\" WHERE machine =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Memory {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "machine" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "memory_usage",
     "query": "SELECT \"value\" FROM \"memory_usage\" WHERE \"container_name\" =~ /^$container$/ AND \"machine\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$*/" },
      { "condition": "AND", "key": "machine", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "CPU {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "machine" ], "type": "tag" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "cpu_usage_total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container$*/" },
      { "condition": "AND", "key": "machine", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Usage {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "machine" ], "type": "tag" }
     ],
     "measurement": "fs_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$container$*/" }
     ]
    },
    {
     "alias": "Limit {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "machine" ], "type": "tag" }
     ],
     "measurement": "fs_limit",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$container$*/" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "RX {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "machine" ], "type": "tag" }
     ],
     "measurement": "rx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$container$*/" }
     ]
    },
    {
     "alias": "TX {host: $tag_machine, container: $tag_container_name}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "machine" ], "type": "tag" }
     ],
     "measurement": "tx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "machine", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "container_name", "operator": "=~", "value": "/^$container$*/" }
     ]
    }
   ]
  }
 ]
}